name: CI
on:
  pull_request:
    types:
      - synchronize

jobs:
  rules:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1
      - uses: denoland/setup-deno@v1
      - run: bun install
      - run: bun run knip
      - run: bun run test
