name: Merge
on:
  push:
    branches: [main]

jobs:
  rules:
    runs-on: ubuntu-latest
    steps:
      - uses: ./steps/rules.yml@v1
  schedule:
    runs-on: ubuntu-latest
    steps:
      - uses: ./steps/schedule.yml@v1
