name: Merge
on:
  push:
    branches: [main]

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1
      - uses: denoland/setup-deno@v1
      - run: bun install --production
      - run: bun run schedule
