name: Schedule
on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  schedule:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
      - uses: oven-sh/setup-bun@v1
      - uses: denoland/setup-deno@v1
      - run: bun install
      - run: bun run schedule
