name: Schedule
on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  schedule:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
      - uses: ./steps/schedule.yml@v1
