name: Test
on:
  push:
    branches: [main]

jobs:
  check-inactivity:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
      - name: Check for inactivity
        id: check_inactivity
        run: |
          now=$(date +%s)
          last_commit_timestamp=$(date -d "$last_commit_date" +%s)
          difference=$((now - last_commit_timestamp))
          desired_inactivity_seconds=$DESIRED_INACTIVITY_SECONDS + ($DESIRED_INACTIVITY_MINUTES * 60) + ($DESIRED_INACTIVITY_HOURS * 60 * 60) + ($DESIRED_INACTIVITY_DAYS * 24 * 60 * 60)

          if [[ $difference -gt $desired_inactivity_seconds ]]; then
            echo "No commits in the last 24 hours!"
            echo "no_commits=true" >> $GITHUB_OUTPUT
          else
            echo "Recent commit detected. Skipping script."
          fi
        env:
          DESIRED_INACTIVITY_SECONDS: 0
          DESIRED_INACTIVITY_MINUTES: 2
          DESIRED_INACTIVITY_HOURS: 0
          DESIRED_INACTIVITY_DAYS: 0
  run:
    runs-on: ubuntu-latest
    needs: check-inactivity
    if: ${{ needs.check-inactivity.outputs.no_commits == 'true' }}
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
      - uses: oven-sh/setup-bun@v1
      - uses: denoland/setup-deno@v1
      - run: bun install --production
      - run: bun run schedule
